---
collections:
  - name: amazon.aws
  - name: community.crypto
    version: 2.24.0
  - name: community.dns
    version: 3.1.2
  - name: community.hashi_vault
    version: 6.2.0
  - name: f5networks.f5_modules
  - name: redhat.rhel_system_roles
